apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
      <meta charset="UTF-8">
      <title>DevOps App</title>
    </head>
    <body>
      <h1>Frontend funcionando!</h1>
      <p>Consuma o backend: <a href="http://localhost:30000/ping">/ping</a></p>
    </body>
    </html>
